config/routes.rb
Rails.application.routes.draw do
  root 'movies#welcome'

  resources :movies, :actors
  get 'about' => 'movies#about'
  

end

app/models/actor.rb
class Actor < ActiveRecord::Base

end

app/models/description.rb
class Description < ActiveRecord::Base
belongs_to :movie
end

app/models/movie.rb
class Movie < ActiveRecord::Base
has_many :descriptions
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
	layout 'actor' 
	def index
	 
		@actors=Actor.all
	end
	def new
		@actor=Actor.new
		
	end
	def create
	 	actor=Authentication.new(actor_params) #using service objects
	 	#actor=Actor.new(actor_params)
	 	#actor.save
	 	redirect_to actors_path
	end	
  
  def show
		
		@actor=Actor.find_by_id(params[:id])
	end


	def edit
  	
	 	if params[:id].present?
	 		@actor=Actor.find_by_id(params[:id])
	 	end
	end		
	def update
		actor=Actor.find_by_id(params[:id])
		actor.update(actor_params)
		redirect_to actors_path
	end	

	def destroy
		
	 	actor=Actor.find_by_id(params[:id])
    actor.delete
    redirect_to actors_path
  end 

	private

	  def actor_params
	  	params.require(:actor).permit(:name,:movie)
	  end
end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	layout 'movie'
	def index
	 
		@movies=Movie.all
	end	
	def show
		
		@movie=Movie.find_by_id(params[:id])
	end
	def welcome
		
	end		
	def new
			 

		@movie=Movie.new
		
	end
  def edit
  		 

	 	if params[:id].present?
	 		@movie=Movie.find_by_id(params[:id])
	 	end
	end		
	def update
  	 

		movie=Movie.find_by_id(params[:id])
		movie.update(movie_params)
		redirect_to movies_path
	end	

	def destroy
 	 
		
	 	movie=Movie.find_by_id(params[:id])
    movie.delete
    redirect_to movies_path
  end 
 
	def create
    HEAD
		#create record

	 	

	 	movie=Movie.new(movie_params)
	 	movie.save
	 	redirect_to movies_path
	end	
	
	def about
	 

  
	end	

	 private

	  def movie_params
	  	params.require(:movie).permit(:name,:year)
	  end
			
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/views/actors/edit.html.erb
<%=render 'shared/form'%>

app/views/actors/index.html.erb
<html>
 <body>
  <h1>Actor Details</h1>
   
   <%@actors.each do |actor|%>
   <li><a href="<%=actor_path(actor.id)%>"><%=actor.name%>(<%=actor.movie%>)</a></li>
   <%end%>
 </body>
</html>   

app/views/actors/new.html.erb
<%=render 'shared/form'%>

app/views/actors/show.html.erb
<html>


<body>
<h1>Movie Details</h1>
<br>
<p><b>Name:</b><%=@actor.name%></p>
<p><b>Movie:</b><%=@actor.movie%></p>
<%=link_to "Edit Actor", edit_actor_path(@actor.id)%>
<%=link_to "Delete", actor_path(@actor), :method=> "DELETE"%>

</body>
</html>

app/views/layouts/actor.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Actor Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<style>
  html { font-family: Arial;background:rgb(255,170,20); }
  body { padding: 10px 30px; }
  h1 { font-size: 2.5em; font-family:Verdana;color:rgb(220,80,23);text-align: center;background:white;}
  h2 { font-size: 1.2em; }
  nav { background: black; padding: 5px; }
nav ul { list-style: none; }
nav ul li { display: inline; margin-left: 15px; font-weight: bold; }
nav ul li a { color: white; }
nav ul li a:visited { color: white; }
nav ul li a:hover { color: orange; }
a { text-decoration: italic; color: blue; }
a:visited { color:purple; }
a:hover { color: red; }
img{margin-left: 150px;}
</style>
</head>
<body>

<%=render 'shared/top_nav'%> 


<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>MoviesProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/movie.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>MoviesProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<style>
  html { font-family: Arial;background:rgb(255,170,20); }
  body { padding: 10px 30px; }
  h1 { font-size: 2.5em; font-family:Verdana;color:rgb(220,80,23);text-align: center;background:white;}
  h2 { font-size: 1.2em; }
  nav { background: black; padding: 5px; }
nav ul { list-style: none; }
nav ul li { display: inline; margin-left: 15px; font-weight: bold; }
nav ul li a { color: white; }
nav ul li a:visited { color: white; }
nav ul li a:hover { color: orange; }
a { text-decoration: italic; color: blue; }
a:visited { color:purple; }
a:hover { color: red; }
img{margin-left: 150px;}
</style>
</head>
<body>
<%if params[:action]!= "welcome"%>
<%=render 'shared/top_nav'%> 
<%end%>

<%= yield %>

</body>
</html>

app/views/movies/about.html.erb
<html>
<body>
 <h1>About Screen</h1>
 <p>Movies World has been prepared for the people to store their memorable moments of life which is mostly when people watch movies with their friends and family.</p>
 <p> So,you can store your memories and at the end of the year you can remember those memories and enjoy every year of your life.</p>

</body>
</html>

app/views/movies/edit.html.erb
<%=render 'shared/form'%>

app/views/movies/index.html.erb
<html>


<body>
	<h1>Movies World</h1>

<section id=”content”> 
 <h2>Upcoming Movies</h2>
  <div>
  
   <p>
   	<ul>
   		<li><a href="http://www.bollymoviereviewz.com/2011/12/upcoming-bollywood-movies-2012-release.html">This Year</a></li>
   	</ul>You can keep your memories alive by adding your experience while watching a movie.</p>
   <p>At the end of the year you will recall these wonderful moments and enjoy every year of your life...</p>  
  </div>
  <div>
     
   <h2>Movies Watched This Year</h2>
   <p>
   	<img src="http://www.makingdifferent.com/wp-content/uploads/2013/03/Movies.gif" width="200" height="200" title="Memories"/>
   	</p>
    
    <%@movies.each do |movie|%>
   	<li><a href="<%=movie_path(movie.id)%>"><%=movie.name%>(<%=movie.year%>)</a></li>
    <%end%>

   	  
  </div>
</section>
</body>

</html>

app/views/movies/new.html.erb
<%=render 'shared/form'%>
	

app/views/movies/show.html.erb
<html>


<body>
<h1>Movie Details</h1>
<br>
<p><b>Movie:</b><%=@movie.name%></p>
<p><b>Year:</b><%=@movie.year%></p>
<%=link_to "Edit Movie", edit_movie_path(@movie.id)%>
<%=link_to "Delete", movie_path(@movie), :method=> "DELETE"%>

</body>
</html>

app/views/movies/welcome.html.erb
<html>

<body>
	<h1>Welcome to Movies World</h1>
	<br>
	<br>
	<p>
   	<img src="http://ajinkyapokharkar.files.wordpress.com/2013/02/best-bollywood-movies-of-2012.jpg" width="1000" height="500" title="Memories"/>
 	</p>
	<p align="center">You can add new movies and view your movies here:</p>
  <div style="text-align: center">
   <a href="<%=movies_path%>" align="center">Movies World</a>
  </div>
</body>
</html>

app/views/shared/_form.html.erb
<%if params[:controller]== "movies"%>
<%=form_for @movie do |f|%>
	
	Movie:<%=f.text_field :name%><br>
	Year:<%=f.text_field :year%><br>
	<%=f.submit "Submit"%>
	<%end%>
<%else%>
  <%=form_for @actor do |f|%>
	
	Name:<%=f.text_field :name%><br>
	Movie:<%=f.text_field :movie%><br>
	<%=f.submit "Submit"%>
	<%end%>	
<%end%>	

app/views/shared/_top_nav.html.erb
<nav>
	<ul>
	 <li><%=link_to "Home",root_path%></li>
	 <li><%=link_to "About" , about_path%></li>
	 <li><%=link_to "Add New Movie",new_movie_path%></li>
	 <li><%=link_to "Add New Actor",new_actor_path%></li>
	 <li><%=link_to "Actors List" ,actors_path%></li>
	</ul>
</nav>